- name: Ubuntu WSL Configuration
  hosts: localhost
  tasks:
    - name: Install required snap packages
      snap:
        name:
          - gh
          - rustup
          - ripgrep
            #         - tmux
            #         - fzf
            #         - rustup
            #         - eza
            #         - ripgrep
            #         - bat
            #         - starship
            #         - sccache
            #         - unzip
            #         - github-cli
            #         - fontconfig
            #         - ttf-jetbrains-mono-nerd

        state: present
        classic: true
      become: true
    - name: Install required apt packages
      apt:
        name:
          - fzf
          - unzip
          - fontconfig
          - build-essential
          - cmake
          - tree
        state: latest
      become: true
    - name: Setup rustlang with rustup
      ansible.builtin.shell:
        cmd: rustup install stable
    - name: Install starship
      ansible.builtin.shell:
        cmd: cargo install starship
        creates: ~/.cargo/bin/starship
    - name: Install eza
      ansible.builtin.shell:
        cmd: cargo install eza
        creates: ~/.cargo/bin/eza
    - name: Install bat
      ansible.builtin.shell:
        cmd: cargo install bat
        creates: ~/.cargo/bin/bat
        #    - name: Install jumper
        #      ansible.builtin.shell:
        #        cmd: cargo install jumper
        #        creates: ~/.cargo/bin/jumper
        #
    - name: Install neovim
      become: true
      ansible.builtin.script: ../scripts/install_nvim.sh

