- name: Arch WSL Configuration
  hosts: localhost
  tasks:
    - name: Install required packages
      pacman:
        name:
          - neovim
          - tmux
          - fzf
          - rustup
          - eza
          - ripgrep
          - bat
          - starship
        state: latest
        update_cache: yes
      become: true
    - name: Setup rustlang with rustup
      ansible.builtin.shell:
        cmd: rustup install stable
    - name: Install jumper
      ansible.builtin.shell:
        cmd: cargo install jumper
        creates: ~/.cargo/bin/jumper
