--return {
--    'renerocksai/telekasten.nvim',
--    dependencies = {'nvim-telescope/telescope.nvim', 'renerocksai/calendar-vim'},
--    config = function ()
--        require('telekasten').setup({
--            home = vim.fn.expand("~/notes")
--        })
--
--        local wk = require('which-key')
--        wk.add({
--            {"<leader>f", desc = "Telekasten"},
--            {"<leader>fp", "<cmd>Telekasten panel<CR>", desc = "Show panel"}},
--            {"<leader>ff", "<cmd>Telekasten find_notes<CR>", desc = "Find notes"}},
--            {"<leader>fs", "<cmd>Telekasten search_notes<CR>", desc = "Search notes"}},
--            {"<leader>ft", "<cmd>Telekasten show_tags<CR>", desc = "Search tags"},
--            {"<leader>fn", "<cmd>Telekasten new_note<CR>", desc = "Create a new note"},
--            {"<leader>fo", "<cmd>Telekasten goto_today<CR>", desc = "Open todays daily note"},
--            {"<leader>fc", "<cmd>Telekasten show_calendar<CR>", desc = "Show the calendar"},
--            {"<leader>fb", "<cmd>Telekasten show_backlinks<CR>", desc = "Show backlinks"},
--            {"<leader>fi", "<cmd>Telekasten insert_link<CR>", desc = "Insert link"},
--            {"<leader>fg", "<cmd>Telekasten follow_link<CR>", desc = "Follow link"},
--        })
--
--        vim.api.nvim_create_autocmd({"BufEnter"}, {
--            pattern = {"/home/marad/notes/**.md"},
--            callback = function()
--                vim.keymap.set("n", "<CR>", "<cmd>Telekasten follow_link<CR>")
--                vim.keymap.set("n", "<BS>", "<cmd>b#<CR>")
--                vim.keymap.set("i", "[[", "<cmd>Telekasten insert_link<CR>")
--                vim.keymap.set("i", "<C-CR>", "<cmd>Telekasten toggle_todo<CR>")
--                vim.keymap.set("n", "<C-CR>", "<cmd>Telekasten toggle_todo<CR>")
--            end
--        })
--
--        vim.cmd("set conceallevel=2")
--        vim.cmd("hi tkLink guifg=Cyan gui=underline")
--        vim.cmd("hi tkAliasedLink guifg=Cyan gui=underline")
--
--        --vim.keymap.set("n", "<CR>", "<cmd>Telekasten follow_link<CR>")
--        --vim.keymap.set("i", "[[", "<cmd>Telekasten insert_link<CR>")
--
--
--        --vim.cmd("set conceallevel=2")
--        --vim.cmd("hi tkLink guifg=Cyan gui=underline")
--        --vim.cmd("hi tkAliasedLink guifg=Cyan gui=underline")
--        --vim.cmd("hi tkBrackets guifg=gray")
--    end,
--}
return {}
